language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="1.0" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- rvm get stable
- chmod a+x ./TravisBuild/*.sh

install:
- cat /etc/hosts
- ./TravisBuild/install-unity.sh

script:
- ./TravisBuild/build.sh
